### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jqnatividad** [WPRDC/WPRDC-dashboard#1]
We'd love to bring this innovation to other jurisdictions and contribute back to developing the dashboard.

However, there is no license file in the repo...

**Comment by drw** [comment]
I thought about using various alternative licenses (such as the Beerware license), but I decided to go with the standard MIT License for its simplicity, permissiveness, and unambiguousness: https://github.com/WPRDC/WPRDC-dashboard/commit/3ebe713d1f24b641c99f25ae07944df56139296d

However (and particularly in future generalized variants), crediting the Western Pennsylvania Regional Data Center for supporting the development of this dashboard software would certainly be appreciated.

**Comment by jqnatividad** [comment]
Awesome!  Will be to sure to give credit where its due when we do deploy it elsewhere!  Thanks!  Will promote it to the CKAN community as well.
